name: shax
description: Online shop and modeling application.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  equatable: ^2.0.3
  flutter_redux: ^0.8.2
  redux: ^5.0.0
  adjust_sdk: ^4.29.2
  core:
    path: core
  package_info_plus: ^1.0.4
  navigation_history_observer: ^1.1.0
  flutter_bloc: ^8.0.1
  get_it: ^7.2.0
  get_storage:
  flutter_spinkit: ^5.1.0
  hive_flutter: ^1.1.0
  retrofit: ^3.0.1+1
  json_annotation:
  dio: ^4.0.6
  progress_state_button: ^1.0.4
  email_validator: ^2.0.1
  google_nav_bar: ^5.0.6
  infinite_scroll_pagination: ^3.1.0
  pull_to_refresh: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  retrofit_generator: ^4.0.1
  build_runner: ^2.1.8
  json_serializable: ^6.1.5

flutter:
  uses-material-design: true

  assets:
    - assets/images/