name: core
publish_to: none
description: Globally used functionality.

version: 0.0.1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get_it: ^7.1.3
  equatable: ^2.0.3
  logger: ^1.1.0
  synchronized: ^3.0.0+2
  path_provider: ^2.0.9
  device_info_plus: ^3.2.2
  flutter_secure_storage: ^5.0.2
  flutter_native_timezone: <=2.0.0
  dio: ^4.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
