// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCn3dj1ypIW5k_9EjRNwXCuGDMZ4ezXY38',
    appId: '1:845426604597:web:2bb8732ceb12276f2c0f7c',
    messagingSenderId: '845426604597',
    projectId: 'my-shax',
    authDomain: 'my-shax.firebaseapp.com',
    storageBucket: 'my-shax.appspot.com',
    measurementId: 'G-F7PF8ST5L9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDINtORYUg5RnSexV_ETVVtjzxC6Xlw6Do',
    appId: '1:845426604597:android:2ab0cbafa257c5412c0f7c',
    messagingSenderId: '845426604597',
    projectId: 'my-shax',
    storageBucket: 'my-shax.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQPlSyX0eh3lfu-AL-WSUUuFhQsSH7O4s',
    appId: '1:845426604597:ios:186e82241738eeef2c0f7c',
    messagingSenderId: '845426604597',
    projectId: 'my-shax',
    storageBucket: 'my-shax.appspot.com',
    iosClientId: '845426604597-4f84ei5084h0bq24aeeoci2ouulejvjn.apps.googleusercontent.com',
    iosBundleId: 'com.artin.mrt.shax',
  );
}
